general:
  name: "model"
  folder: "./agents/"
  training: False

environment:
  model: "model/new_model.xml"
  kinematics: "data/1.csv"
  train_ratio: 0.8
  seed: 42
  path_steps: 0
  w_bone_diff: 100.0
  w_elbow: 1.0
  w_paw: 1.0
  w_effort: 0.0
  w_qpos: 0.0
  w_qvel: 0.0
  w_action: 0.0
  control_dt: 0.006666666
  n_substeps: 16

model:
  rnn_type: "lstm"
  rnn_hidden_size: 128
  rnn_layers: 1

  policy_hidden_size: 64
  policy_layers: 1

  value_hidden_size: 64
  value_layers: 1

  sequence_length: 50

algorithm:
  learning_rate: 0.001

  n_mini_batches: 10
  n_epochs: 20

  discount_factor: 0.99999
  gae_lambda: 0.95

  clip_range: 0.2
  clip_range_vf: 0.2

  ent_coef: 0.0
  vf_coef: 0.5

  max_grad_norm: 0.5

  kl_threshold: 0
  lr_scheduler_kl_threshold: 0.016

training:
  timesteps: 1_000_000
  num_envs: 1

  write_interval: 1000
  checkpoint_interval: 1000

  rollout_length: 16000

testing:
  step_delay: 0.1
