general:
  name: ""

environment:
  model: ""
  kinematics: ""
  train_ratio: 0.8
  seed: 42
  path_steps: 0
  w_bone_diff: 100.0
  w_elbow: 1.0
  w_paw: 1.0
  w_effort: 0.0
  w_qpos: 0.0
  w_qvel: 0.0
  w_action: 0.0
  control_dt: 0.006666666
  n_substeps: 16

policy:
  lstm_hidden_size: 512
  n_lstm_layers: 1
  net_arch_pi: [128, 128]
  net_arch_vf: [128, 128]

algorithm:
  learning_rate: 0.0001

  n_steps: 512
  batch_size: 512
  n_epochs: 20

  gamma: 0.99
  gae_lambda: 0.95

  clip_range: 0.2
  clip_range_vf: 0.2

  ent_coef: 0.0
  vf_coef: 0.5

  max_grad_norm: 0.5

training:
  timesteps: 2_500_000
  num_envs: 16
  eval_freq: 15_000

testing:
  slowmo: 0.1
