general:
  name: "MODEL_NAME"

environment:
  model: "MODEL_FILE.xml"
  kinematics: "KINEMATIC_FILE.csv"
  w_bone_diff: 1.0
  w_elbow: 1.0
  w_paw: 1.0
  w_effort: 0.0
  w_jitter: 0.0
  w_action: 0.000
  control_dt: 0.006666666
  n_substeps: 16

policy:
  lstm_hidden_size: 256
  n_lstm_layers: 1
  net_arch_pi: [64, 64]
  net_arch_vf: [64, 64]

algorithm:
  learning_rate: 0.0001

  n_steps: 256
  batch_size: 256
  n_epochs: 20

  gamma: 0.99
  gae_lambda: 0.95

  clip_range: 0.2
  clip_range_vf: 0.2

  ent_coef: 0.0
  vf_coef: 0.5

  max_grad_norm: 0.5

training:
  timesteps: 1_000_000
  num_envs: 16

testing:
  slowmo: 0.1
